apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage
  description: Backstage IDP Portal

  annotations:
    github.com/project-slug: vitor-savicki/backstage
    backstage.io/techdocs-ref: value
    backstage.io/kubernetes-namespace: backstage
spec:
  type: openapi
  lifecycle: production
  system: backstage
  owner: group:sre-team
  providesApis:
    - backstage.vitorsavicki.com
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: https://backstage.vitorsavicki.com/
    paths:
      /artists:
        get:
          summary: List all artists