apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: teste
  description: Backstage
  tags:
    - teste
    - teste
  links:
    - url: https://teste.vitor-savicki.eti.br
      title: System
      icon: dashboard
  annotations:
    github.com/project-slug: vitor-savicki/teste
    backstage.io/kubernetes-namespace: teste
spec:
  type: system
  owner: group:vitor-savicki
  domain: teste