appName: ${{values.component_id}}
userGivenName: ${{values.component_id}}
destNamespace: ${{values.component_id}}
destServer: https://kubernetes.default.svc
srcPath: ''
repoURL: https://vitor-savicki.github.io/helm-charts
srcRepoURL: https://vitor-savicki.github.io/helm-charts
srcTargetRevision: '0.1.3'
labels:
exclude: ''
include: ''
helm:
  chart: web-application
  valueFiles: values
  values: |-
      fullnameOverride: ${{values.component_id}}
      image:
        repository: vitorsavicki/${{values.component_id}}
        tag: latest